# Generated by Django 2.2.3 on 2019-08-30 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='time',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='time',
            new_name='endtime',
        ),
        migrations.AddField(
            model_name='notice',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='status',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
