# Generated by Django 2.2.3 on 2019-08-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_home_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='name',
            new_name='address',
        ),
    ]
