# Generated by Django 2.2.3 on 2019-08-30 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190831_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='home_No',
            new_name='home_id',
        ),
    ]
