# Generated by Django 2.2.3 on 2019-09-01 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_notice_home_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='message_endtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='home',
            name='message_starttime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
